### ISSUE TITLE
Change Manifest

### ISSUE THREAD

**Issue by matteobachetti** [matteobachetti/psrsearch.jl#4]
Following @giordano 's comment in #1:

> I didn't touch the Manifest.toml files, but personally I don't find them very useful for packages: they're picked up by CI jobs, which effectively prevents you from testing the package with different versions of the dependencies, as they come out.

I need to understand how that works without Manifest.

**Comment by matteobachetti** [comment]
Fixed by eliminating the file :)

**Comment by giordano** [comment]
You already deleted the manifests, but let me elaborate a bit more.

I don't know how you're adding/removing dependencies to the package, the canonical way is to activate the environment with the package manager (`]` is to enter [Pkg REPL mode](https://julialang.github.io/Pkg.jl/v1/repl/), you can leave the mode by pressing backspace, you can think of it like "delete the `]`")
```julia
]activate /path/to/the/package/directory
```
To go back to the top-level environment, use `activate` without arguments in the Pkg REPL mode.

I assume you're already doing something like this, since you have the manifests, which are automatically created by the package manager when you add/remove packages to the environment.  My suggestion is to simply ignore manifests in packages' repositories and not commit them, for the reasons quoted above.
